### ISSUE TITLE
Set up MongoDB for InviteX Backend

### ISSUE THREAD

**Issue by onkar69483** [onkar69483/InviteX#1]
We need to configure MongoDB as the database for the backend of InviteX. This will involve setting up a connection, adding environment variables, and testing the setup with a sample database.

---

#### Tasks  
- [x] **Install MongoDB**  
  - Install MongoDB locally, or set up a cluster using [MongoDB Atlas](https://www.mongodb.com/atlas/database).  
  - Obtain the connection string for the database.  

- [x] **Create a connection file**  
  - Create a `db.js` file in the `backend` folder.  
  - Use the `mongoose` library to connect to MongoDB.  
  - Load the connection string from an environment variable in the `.env` file.  

- [x] **Add `.env` file**  
  - Add the following line to the `.env` file with the correct MongoDB URI:  
    ```plaintext
    MONGO_URI=mongodb://<username>:<password>@cluster0.mongodb.net/invitex?retryWrites=true&w=majority
    ```  

- [x] **Integrate connection in `app.js`**  
  - Import the connection logic in `app.js` and initialize the connection on server startup.  

- [x] **Test the connection**  
  - Create a test schema in `models/` (e.g., `Test.js`).  
  - Write a route to save and fetch a sample document to ensure MongoDB is working.

---

#### Acceptance Criteria  
- [x] MongoDB connection is successfully established.  
- [x] Environment variables are used for sensitive information.  
- [x] Test schema and routes verify the functionality.  
- [x] Proper error handling is implemented for failed connections.

**Comment by CodingDevil081** [comment]
I'll handle it
